## Unit + integration tests for the ElevenLabs GuiAssert plugin.
##
## ## Pure tests (always run)
##
##   * `elevenlabsAuthHeader` produces an `HttpHeaders` carrying the
##     documented lowercase `xi-api-key` value (no `Authorization`
##     header, no `Bearer ` prefix),
##   * `buildTtsBody` emits the expected JSON shape (`text`,
##     `model_id`, `voice_settings.stability`,
##     `voice_settings.similarity_boost`),
##   * `resolveApiKey` / `resolveApiBase` / `resolveModelId` /
##     `resolveVoiceId` / `resolveStability` / `resolveSimilarityBoost`
##     honour providerSettings -> env-var / default precedence,
##   * `elevenlabsProvider()` is wired up with the canonical name +
##     non-nil callbacks,
##   * `registerElevenLabs` integrates with the registry,
##   * `isAvailable()` reflects the presence of `ELEVENLABS_API_KEY`,
##   * cache-key determinism + per-input sensitivity (different
##     `voice_id` / `model_id` / sample rate / stability -> different
##     key).
##
## ## Mock-server integration test (always run, no network)
##
## A `std/asynchttpserver` mock spun up on a random free localhost
## port mirrors ElevenLabs's `POST /v1/text-to-speech/{voice_id}`
## endpoint.  The mock records every request (method, path, headers,
## body) so the test can then assert — by exact value — that the
## provider sent the `xi-api-key` header and the JSON body shape
## ElevenLabs expects.  The mock returns a 1-second silent MP3
## generated by ffmpeg as the "TTS result"; the test then verifies
## the provider's downloaded WAV is a valid 16-bit PCM mono RIFF WAV
## via ffprobe, and that a second invocation hits the on-disk cache
## and skips all HTTP.
##
## ## Live test (compile-time-gated via `-d:elevenlabsLive`)
##
##   nim c -d:elevenlabsLive -r --threads:on --hints:off \
##       --path:src --path:../GuiAssert/src tests/televenlabs.nim
##
## Requires `ELEVENLABS_API_KEY` to be set.  Per project policy, the
## live suite never silently skips: a missing key is a test failure.

import std/[asynchttpserver, asyncdispatch, httpcore, json,
            net, options, os, osproc, streams, strformat, strutils,
            tables, times, unittest]

import gui_assert/speech_synthesis
import gui_assert_elevenlabs

# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

proc thisRepoRoot(): string =
  ## `currentSourcePath` -> .../GuiAssert-ElevenLabs/tests/televenlabs.nim
  currentSourcePath().parentDir().parentDir()

# ---------------------------------------------------------------------------
# Fixture synthesis
# ---------------------------------------------------------------------------

proc runSh(args: openArray[string]): tuple[code: int, output: string] =
  let bin = findExe(args[0])
  doAssert bin.len > 0, "binary not on PATH: " & args[0]
  var rest: seq[string] = @[]
  for i in 1 ..< args.len: rest.add args[i]
  let p = startProcess(
    command = bin, args = rest, options = {poStdErrToStdOut}
  )
  let raw = p.outputStream.readAll()
  let code = p.waitForExit()
  p.close()
  result = (code: code, output: raw)

proc ensureMockMp3(): string =
  ## Produce a 1-second silent MP3 (~4 KB) that the mock server
  ## returns as the synthesised audio payload.  Synthesised once per
  ## test run under /tmp to keep the repo clean.
  let target = "/tmp/televenlabs-mock-silence.mp3"
  if fileExists(target) and getFileSize(target) > 1024:
    return target
  let ffBin =
    block:
      let env = getEnv("FFMPEG_BIN")
      if env.len > 0 and fileExists(env): env
      else: findExe("ffmpeg")
  doAssert ffBin.len > 0, "ffmpeg missing on PATH; needed by the mock server"
  if fileExists(target): removeFile(target)
  let r = runSh([ffBin, "-hide_banner", "-loglevel", "error", "-y",
                 "-f", "lavfi", "-i", "anullsrc=r=22050:cl=mono",
                 "-t", "1",
                 "-c:a", "libmp3lame", "-b:a", "64k",
                 target])
  doAssert r.code == 0, "ffmpeg mock MP3 synthesis failed: " & r.output
  result = target

# ---------------------------------------------------------------------------
# Pure tests
# ---------------------------------------------------------------------------

suite "elevenlabs auth header":

  test "produces an xi-api-key header carrying the raw key":
    let h = elevenlabsAuthHeader("foo")
    check h.hasKey("xi-api-key")
    check h["xi-api-key"] == "foo"

  test "pins Content-Type: application/json alongside":
    let h = elevenlabsAuthHeader("DUMMY_KEY")
    check h["xi-api-key"] == "DUMMY_KEY"
    check h["Content-Type"] == "application/json"

  test "does not prepend Bearer or Basic to the key":
    let h = elevenlabsAuthHeader("api-key-xyz")
    check h["xi-api-key"] == "api-key-xyz"
    check (not h["xi-api-key"].startsWith("Bearer "))
    check (not h["xi-api-key"].startsWith("Basic "))

  test "does not include any Authorization header":
    # ElevenLabs uses `xi-api-key`, NOT `Authorization`.  Regression
    # guard against accidental copy-paste from a sibling plugin.
    let h = elevenlabsAuthHeader("any-key")
    check (not h.hasKey("Authorization"))

suite "elevenlabs request body":

  test "builds the documented v1 JSON shape":
    let body = buildTtsBody("Hello, this is ElevenLabs.",
                            "eleven_monolingual_v1")
    check body.kind == JObject
    check body["text"].getStr == "Hello, this is ElevenLabs."
    check body["model_id"].getStr == "eleven_monolingual_v1"
    check body["voice_settings"].kind == JObject
    check body["voice_settings"]["stability"].getFloat == 0.5
    check body["voice_settings"]["similarity_boost"].getFloat == 0.5

  test "uses snake_case keys (model_id, voice_settings, similarity_boost)":
    let body = buildTtsBody("hi", "eleven_monolingual_v1")
    check body.hasKey("model_id")
    check body.hasKey("voice_settings")
    check body["voice_settings"].hasKey("similarity_boost")
    check (not body.hasKey("modelId"))
    check (not body.hasKey("voiceSettings"))
    check (not body["voice_settings"].hasKey("similarityBoost"))

  test "honours non-default stability + similarity_boost":
    let body = buildTtsBody("hi", "model_x",
                            stability = 0.75, similarityBoost = 0.25)
    check body["voice_settings"]["stability"].getFloat == 0.75
    check body["voice_settings"]["similarity_boost"].getFloat == 0.25

suite "elevenlabs opts resolution":

  test "resolveApiKey prefers providerSettings over env":
    putEnv(ApiKeyEnvVar, "ENV_KEY")
    let opts = SpeechSynthesisOpts(
      providerSettings: %*{"api_key": "OPTS_KEY"}
    )
    check resolveApiKey(opts) == "OPTS_KEY"
    delEnv(ApiKeyEnvVar)

  test "resolveApiKey falls back to env when providerSettings empty":
    putEnv(ApiKeyEnvVar, "ENV_ONLY")
    let opts = SpeechSynthesisOpts(providerSettings: newJObject())
    check resolveApiKey(opts) == "ENV_ONLY"
    delEnv(ApiKeyEnvVar)

  test "resolveApiKey returns empty when neither set":
    delEnv(ApiKeyEnvVar)
    let opts = SpeechSynthesisOpts(providerSettings: newJObject())
    check resolveApiKey(opts) == ""

  test "resolveApiBase strips trailing slashes":
    let opts = SpeechSynthesisOpts(
      providerSettings: %*{"api_base": "http://x.test:9000///"}
    )
    check resolveApiBase(opts) == "http://x.test:9000"

  test "resolveApiBase defaults to the public ElevenLabs endpoint":
    let opts = SpeechSynthesisOpts(providerSettings: newJObject())
    check resolveApiBase(opts) == DefaultElevenLabsApiBase
    check DefaultElevenLabsApiBase == "https://api.elevenlabs.io"

  test "resolveModelId defaults to eleven_monolingual_v1":
    let opts = SpeechSynthesisOpts(providerSettings: newJObject())
    check resolveModelId(opts) == DefaultElevenLabsModelId
    check DefaultElevenLabsModelId == "eleven_monolingual_v1"

  test "resolveModelId reads providerSettings override":
    let opts = SpeechSynthesisOpts(
      providerSettings: %*{"model_id": "eleven_multilingual_v2"}
    )
    check resolveModelId(opts) == "eleven_multilingual_v2"

  test "resolveVoiceId defaults to Rachel":
    let opts = SpeechSynthesisOpts(providerSettings: newJObject())
    check resolveVoiceId(opts) == DefaultElevenLabsVoiceId
    check DefaultElevenLabsVoiceId == "21m00Tcm4TlvDq8ikWAM"

  test "resolveVoiceId honours opts.voiceId":
    let opts = SpeechSynthesisOpts(
      voiceId: some("MyCustomVoice"),
      providerSettings: newJObject()
    )
    check resolveVoiceId(opts) == "MyCustomVoice"

  test "resolveVoiceId honours providerSettings.voice_id":
    let opts = SpeechSynthesisOpts(
      providerSettings: %*{"voice_id": "AnotherVoice"}
    )
    check resolveVoiceId(opts) == "AnotherVoice"

  test "resolveStability defaults to 0.5; override honoured":
    check resolveStability(
      SpeechSynthesisOpts(providerSettings: newJObject())) == 0.5
    check resolveStability(SpeechSynthesisOpts(
      providerSettings: %*{"stability": 0.75})) == 0.75

  test "resolveSimilarityBoost defaults to 0.5; override honoured":
    check resolveSimilarityBoost(
      SpeechSynthesisOpts(providerSettings: newJObject())) == 0.5
    check resolveSimilarityBoost(SpeechSynthesisOpts(
      providerSettings: %*{"similarity_boost": 0.25})) == 0.25

suite "elevenlabs provider value":

  test "elevenlabsProvider builds a provider with the canonical name":
    let p = elevenlabsProvider()
    check p.name == ProviderName
    check p.name == "elevenlabs"
    check (not p.isAvailable.isNil)
    check (not p.synthesize.isNil)

  test "registerElevenLabs exposes the plugin via the registry":
    let r = newDefaultSpeechRegistry()
    check (not hasSpeechProvider(r, "elevenlabs"))
    registerElevenLabs(r)
    check hasSpeechProvider(r, "elevenlabs")
    let got = getSpeechProvider(r, "elevenlabs")
    check got.name == "elevenlabs"
    # The host-OS built-in must remain registered.
    when defined(macosx):
      check hasSpeechProvider(r, "say")

suite "elevenlabs isAvailable":

  test "returns false when ELEVENLABS_API_KEY is unset":
    delEnv(ApiKeyEnvVar)
    check (not elevenlabsIsAvailable())

  test "returns true when ELEVENLABS_API_KEY is set":
    putEnv(ApiKeyEnvVar, "anything-nonempty")
    check elevenlabsIsAvailable()
    delEnv(ApiKeyEnvVar)

suite "elevenlabs cache key":

  test "same inputs produce the same key":
    let salt = elevenlabsCacheSalt(DefaultElevenLabsModelId, 22050,
                                   0.5, 0.5)
    let k1 = speechCacheKeyFor("hi", ProviderName,
                              DefaultElevenLabsVoiceId, salt)
    let k2 = speechCacheKeyFor("hi", ProviderName,
                              DefaultElevenLabsVoiceId, salt)
    check k1 == k2
    check k1.len == 16

  test "different text -> different key":
    let salt = elevenlabsCacheSalt(DefaultElevenLabsModelId, 22050,
                                   0.5, 0.5)
    let k1 = speechCacheKeyFor("hello", ProviderName,
                              DefaultElevenLabsVoiceId, salt)
    let k2 = speechCacheKeyFor("goodbye", ProviderName,
                              DefaultElevenLabsVoiceId, salt)
    check k1 != k2

  test "different voice_id -> different key":
    let salt = elevenlabsCacheSalt(DefaultElevenLabsModelId, 22050,
                                   0.5, 0.5)
    let k1 = speechCacheKeyFor("hi", ProviderName,
                              "voice_A", salt)
    let k2 = speechCacheKeyFor("hi", ProviderName,
                              "voice_B", salt)
    check k1 != k2

  test "different model_id -> different salt -> different key":
    let saltA = elevenlabsCacheSalt("eleven_monolingual_v1", 22050,
                                    0.5, 0.5)
    let saltB = elevenlabsCacheSalt("eleven_multilingual_v2", 22050,
                                    0.5, 0.5)
    check saltA != saltB
    let k1 = speechCacheKeyFor("hi", ProviderName,
                              DefaultElevenLabsVoiceId, saltA)
    let k2 = speechCacheKeyFor("hi", ProviderName,
                              DefaultElevenLabsVoiceId, saltB)
    check k1 != k2

  test "different sample rate -> different salt -> different key":
    let saltA = elevenlabsCacheSalt(DefaultElevenLabsModelId, 22050,
                                    0.5, 0.5)
    let saltB = elevenlabsCacheSalt(DefaultElevenLabsModelId, 44100,
                                    0.5, 0.5)
    check saltA != saltB

  test "different stability -> different salt -> different key":
    let saltA = elevenlabsCacheSalt(DefaultElevenLabsModelId, 22050,
                                    0.5, 0.5)
    let saltB = elevenlabsCacheSalt(DefaultElevenLabsModelId, 22050,
                                    0.7, 0.5)
    check saltA != saltB

suite "elevenlabs synthesize input validation":

  test "empty text raises ElevenLabsError":
    putEnv(ApiKeyEnvVar, "DUMMY")
    try:
      let p = elevenlabsProvider()
      let tmp = getTempDir() / "televenlabs_no_text"
      if dirExists(tmp): removeDir(tmp)
      createDir(tmp)
      let outWav = tmp / "out.wav"
      let opts = SpeechSynthesisOpts(
        cacheDir: some(tmp / "cache"),
        providerSettings: newJObject(),
      )
      expect SpeechSynthesisError:
        p.synthesize("", outWav, opts)
    finally:
      delEnv(ApiKeyEnvVar)

  test "missing API key raises SpeechSynthesisError at synthesize time":
    delEnv(ApiKeyEnvVar)
    let p = elevenlabsProvider()
    let tmp = getTempDir() / "televenlabs_no_key"
    if dirExists(tmp): removeDir(tmp)
    createDir(tmp)
    let outWav = tmp / "out.wav"
    let opts = SpeechSynthesisOpts(
      cacheDir: some(tmp / "cache"),
      providerSettings: newJObject(),
    )
    expect SpeechSynthesisError:
      p.synthesize("hi", outWav, opts)

# ---------------------------------------------------------------------------
# Mock-server integration test (no network).
# ---------------------------------------------------------------------------

type
  RecordedRequest = object
    httpMethod: string
    path: string
    query: string
    apiKeyHeader: string
    contentType: string
    accept: string
    body: string

# Shared global state for the mock server.  asynchttpserver's request
# handler is a `proc(req): Future[void]`, which can't easily close
# over per-test locals; globals are the path of least resistance.
var mockRequests: seq[RecordedRequest]
var mockResultMp3Path: string
var mockServerPort: int

proc firstHeader(h: HttpHeaders, name: string): string =
  if h.hasKey(name):
    let vals = h.table[name.toLowerAscii]
    if vals.len > 0: return vals[0]
  return ""

proc mockHandler(req: Request): Future[void] {.async, gcsafe.} =
  {.cast(gcsafe).}:
    var rec = RecordedRequest(
      httpMethod: $req.reqMethod,
      path: req.url.path,
      query: req.url.query,
      apiKeyHeader: firstHeader(req.headers, "xi-api-key"),
      contentType: firstHeader(req.headers, "content-type"),
      accept: firstHeader(req.headers, "accept"),
      body: req.body,
    )
    mockRequests.add rec

    let m = req.reqMethod
    let p = req.url.path

    if m == HttpPost and p.startsWith("/v1/text-to-speech/"):
      let bytes = readFile(mockResultMp3Path)
      await req.respond(Http200, bytes,
                        newHttpHeaders({"Content-Type": "audio/mpeg"}))
      return

    await req.respond(Http404, "mock: no route for " & $m & " " & p,
                      newHttpHeaders({"Content-Type": "text/plain"}))

proc pickFreePort(): int =
  let s = newSocket()
  s.bindAddr(Port(0))
  let (_, port) = s.getLocalAddr
  s.close()
  result = int(port)

var mockServerThread: Thread[int]
var mockServerStopFlag: bool

proc mockServerThreadProc(port: int) {.thread.} =
  {.cast(gcsafe).}:
    let server = newAsyncHttpServer()
    asyncCheck server.serve(Port(port), mockHandler, address = "127.0.0.1")
    while not mockServerStopFlag:
      poll(50)
    server.close()

proc startMockServer(): tuple[port: int, stop: proc() {.gcsafe.}] =
  let port = pickFreePort()
  mockServerPort = port
  mockRequests = @[]
  mockServerStopFlag = false
  createThread(mockServerThread, mockServerThreadProc, port)
  sleep(150)
  let stop = proc() {.gcsafe.} =
    mockServerStopFlag = true
    joinThread(mockServerThread)
  result = (port: port, stop: stop)

proc ffprobeJson(path: string): JsonNode =
  let ffprobe =
    block:
      let env = getEnv("FFPROBE_BIN")
      if env.len > 0 and fileExists(env): env
      else: findExe("ffprobe")
  doAssert ffprobe.len > 0 and fileExists(ffprobe),
    "ffprobe not on PATH; needed by the mock-server + live tests."
  let p = startProcess(
    command = ffprobe,
    args = @["-hide_banner", "-v", "error", "-print_format", "json",
             "-show_streams", "-show_format", path],
    options = {poStdErrToStdOut}
  )
  let raw = p.outputStream.readAll()
  let code = p.waitForExit()
  p.close()
  doAssert code == 0, "ffprobe failed (" & $code & "): " & raw
  parseJson(raw)

suite "elevenlabs mock-server integration":

  test "POST /v1/text-to-speech/{voice} downloads + converts to WAV + caches":
    let mp3 = ensureMockMp3()
    mockResultMp3Path = mp3

    let (port, stop) = startMockServer()
    defer: stop()

    let portStr = $port
    echo &"  mock server listening on http://localhost:{portStr}"

    let provider = elevenlabsProvider()

    let tmp = getTempDir() / "televenlabs_mock"
    if dirExists(tmp): removeDir(tmp)
    createDir(tmp)
    let outWav = tmp / "elevenlabs-mock.wav"
    let opts = SpeechSynthesisOpts(
      voiceId: none(string),
      rate: none(int),
      sampleRateHz: some(22050),
      cacheDir: some(tmp / "cache"),
      providerSettings: %*{
        "api_base": "http://localhost:" & portStr,
        "api_key": "DUMMY_KEY",
      },
      extraArgs: @[],
    )

    let started = epochTime()
    provider.synthesize("Hello from the ElevenLabs mock test.",
                       outWav, opts)
    let dt = epochTime() - started
    echo &"  mock round-trip took {dt*1000:.1f} ms"

    # ----- Recorded-request trace -----
    echo "  recorded requests (", $mockRequests.len, "):"
    for i, r in mockRequests:
      let bodyPreview =
        if r.body.len <= 240: r.body
        else: r.body[0 ..< 240] & " ...(+" & $(r.body.len - 240) &
          " bytes)"
      echo &"    [{i}] {r.httpMethod} {r.path} ?{r.query}"
      echo &"        xi-api-key: {r.apiKeyHeader}"
      echo &"        Content-Type: {r.contentType}"
      echo &"        Accept: {r.accept}"
      echo &"        body[{r.body.len}]: {bodyPreview}"

    # ----- Exactly one HTTP request: ElevenLabs has no polling step -----
    check mockRequests.len == 1

    # ----- Method + path -----
    check mockRequests[0].httpMethod == "POST"
    check mockRequests[0].path ==
      "/v1/text-to-speech/" & DefaultElevenLabsVoiceId

    # ----- xi-api-key header exact-string check -----
    check mockRequests[0].apiKeyHeader == "DUMMY_KEY"
    check mockRequests[0].contentType == "application/json"
    check mockRequests[0].accept == "audio/mpeg"

    # ----- POST body shape -----
    let body = parseJson(mockRequests[0].body)
    check body.kind == JObject
    check body["text"].getStr == "Hello from the ElevenLabs mock test."
    check body["model_id"].getStr == DefaultElevenLabsModelId
    check body["voice_settings"]["stability"].getFloat == 0.5
    check body["voice_settings"]["similarity_boost"].getFloat == 0.5

    # ----- The converted WAV exists, is non-empty, and is a valid
    #       PCM mono RIFF WAV at the requested sample rate -----
    check fileExists(outWav)
    let probe = ffprobeJson(outWav)
    let formatName = probe{"format", "format_name"}.getStr()
    echo &"  WAV format_name: {formatName}"
    check "wav" in formatName.toLowerAscii()
    var hasAudio = false
    var sampleRate = 0
    var channels = 0
    for s in probe{"streams"}.items:
      if s{"codec_type"}.getStr() == "audio":
        hasAudio = true
        let rNode = s{"sample_rate"}
        if not rNode.isNil and rNode.kind == JString:
          sampleRate = parseInt(rNode.getStr())
        channels = s{"channels"}.getInt()
    check hasAudio
    check sampleRate == 22050
    check channels == 1
    let dur = parseFloat(probe{"format", "duration"}.getStr())
    echo &"  WAV duration: {dur:.3f}s, sample_rate: {sampleRate}, " &
         &"channels: {channels}"
    # The mock served a 1-second silent MP3; the converted WAV should
    # be ~1 s ± codec slack.
    check dur >= 0.9
    check dur <= 1.5

    # ----- Cache hit on the second invocation skips HTTP entirely -----
    let beforeCount = mockRequests.len
    let outWav2 = tmp / "elevenlabs-mock-2.wav"
    let secondStart = epochTime()
    provider.synthesize("Hello from the ElevenLabs mock test.",
                       outWav2, opts)
    let secondDt = epochTime() - secondStart
    echo &"  cache-hit second call took {secondDt*1000:.1f} ms"
    check mockRequests.len == beforeCount  # no new HTTP traffic
    check fileExists(outWav2)
    check getFileSize(outWav2) == getFileSize(outWav)

    # ----- Cache miss when the narration text changes -----
    let outWav3 = tmp / "elevenlabs-mock-3.wav"
    provider.synthesize("A completely different narration.",
                       outWav3, opts)
    check mockRequests.len == beforeCount + 1
    check fileExists(outWav3)
    let createBody2 = parseJson(mockRequests[beforeCount].body)
    check createBody2["text"].getStr ==
      "A completely different narration."

# ---------------------------------------------------------------------------
# Live test — compile-time-gated.  Real ElevenLabs API.
# ---------------------------------------------------------------------------
when defined(elevenlabsLive):

  suite "elevenlabs live render against api.elevenlabs.io":

    test "synthesizes a real WAV via the ElevenLabs API":
      doAssert getEnv(ApiKeyEnvVar).len > 0,
        "ELEVENLABS_API_KEY is not set. Live ElevenLabs tests require " &
        "a real API key from https://elevenlabs.io (Starter $5/mo " &
        "includes ~30 min of TTS; Creator $22/mo; Pro $99/mo; " &
        "Scale $330/mo). Export ELEVENLABS_API_KEY=<your key> and " &
        "re-run with -d:elevenlabsLive."

      let tmp = getTempDir() / "televenlabs_live"
      if dirExists(tmp): removeDir(tmp)
      createDir(tmp)

      let r = newDefaultSpeechRegistry()
      registerElevenLabs(r)

      let outWav = tmp / "live.wav"
      let opts = SpeechSynthesisOpts(
        voiceId: none(string),
        rate: none(int),
        sampleRateHz: some(22050),
        cacheDir: some(tmp / "cache"),
        providerSettings: newJObject(),
        extraArgs: @[],
      )

      let started = epochTime()
      synthesizeWith(r, "elevenlabs",
                    "Hello GuiAssert ElevenLabs",
                    outWav, opts)
      let dt = epochTime() - started
      echo &"  live ElevenLabs render took {dt:.2f}s"

      doAssert fileExists(outWav), "no WAV at " & outWav
      let sz = getFileSize(outWav)
      echo &"  output: {sz} bytes"
      check sz > 1024

      let probe = ffprobeJson(outWav)
      let formatName = probe{"format", "format_name"}.getStr()
      check "wav" in formatName.toLowerAscii()

      var hasAudio = false
      for s in probe{"streams"}.items:
        if s{"codec_type"}.getStr() == "audio":
          hasAudio = true
      check hasAudio

      let dur = parseFloat(probe{"format", "duration"}.getStr())
      echo &"  live WAV duration: {dur:.3f}s"
      check dur > 0.5

      # Cache hit — second call must be near-instant.
      let secondStart = epochTime()
      let outWav2 = tmp / "live2.wav"
      synthesizeWith(r, "elevenlabs",
                    "Hello GuiAssert ElevenLabs",
                    outWav2, opts)
      let secondDt = epochTime() - secondStart
      echo &"  second call (cache hit) took {secondDt:.3f}s"
      check secondDt < 5.0
      check fileExists(outWav2)
      check getFileSize(outWav2) == getFileSize(outWav)
